apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql
  namespace: webapps

spec:
  replicas: 1

  selector:
    matchLabels:
      app: db

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: db

    spec:
      containers:
        - name: mysql
          image: mysql:8

          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE

          ports:
            - containerPort: 3306

          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data

          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - 127.0.0.1
            initialDelaySeconds: 30
            periodSeconds: 10

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
